import React from 'react'
import Head from '../../node_modules/next/head'
import Link from '../../node_modules/next/link';
import { Container } from '../styles/pages/Home'
import Create from './transaction/create';
import Find from './transaction/find';

const Home: React.FC = () => {
  return (
    <Container>
      <Head>
        <title>Homepage</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <p>Olá Arthur, bem vindo!</p>

      <h1>Transferências</h1>


<Link href={'/transaction/create'}><button>Nova</button></Link>
<br />
<Link href={'/transaction/find'}><button>Lista</button></Link>



      Criação e consulta de transações

    </Container>
  )
}


export default Home